Updated chirp logic in stashcp

diff --git a/bin/stashcp b/bin/stashcp
--- a/bin/stashcp
+++ b/bin/stashcp
@@ -95,18 +95,20 @@ which condor_chirp
 res=$?
 #echo "which returned with $res"
 if [ $res -ne 0 ]; then
-	cd ../../
-	#echo "Finding..."
-	pd=$(find . | grep "condor_chirp")
-	if [ -z $pd ]; then
-		#echo "Hoping that it's in /usr/libexec/condor"
+	if [ -s /usr/libexec/condor/condor_chirp ]; then
 		PATH=$PATH:/usr/libexec/condor
 	else
-		#echo "Trying non-usr option"
-		p1=$(echo $pd | cut -c 2-)
-		p2=$(echo $p1 | rev | cut -d'/' -f2- | rev)
-		cwd=$(pwd)
-		PATH=$PATH:$cwd/$p2
+		cd ../../
+		pd=$(find . | grep "condor_chirp")
+		if [ -z $pd ]; then
+			echo "condor_chirp not found" >&2
+		else
+			#echo "Trying non-usr option"
+			p1=$(echo $pd | cut -c 2-)
+			p2=$(echo $p1 | rev | cut -d'/' -f2- | rev)
+			cwd=$(pwd)
+			PATH=$PATH:$cwd/$p2
+		fi
 	fi
 	cd -
 fi
