working on closeness code

diff --git a/bin/stashcp b/bin/stashcp
--- a/bin/stashcp
+++ b/bin/stashcp
@@ -15,11 +15,12 @@ function getClose {
 	## for now, call Ilija's code, and hope that it is available nearby
 	setStashCache=`which setStashCache.sh 2>/dev/null`
 	if [ $? -ne '0' ]; then
-		>&2 echo "Cannot find setStashCache.sh, setting to defaults"
+		>&2 echo "Cannot find setStashCache.sh, setting to defaults - PROBLEM"
 		echo "root://data.ci-connect.net"
 		exit 1
 	else 	
-		source $setStashCache 2>&1 > /dev/null
+		cl=$(source $setStashCache)
+		export $STASHPREFIX=$cl
 		echo $STASHPREFIX
 	fi
 }
