testing timeout

diff --git a/bin/stashcp b/bin/stashcp
--- a/bin/stashcp
+++ b/bin/stashcp
@@ -106,34 +106,34 @@ function doStashCpSingle {
 			## Third attempt
 			## Timeout has been made longer
 			#tm=$((tm*10))
-			hn="root://data.ci-connect.net"
-			st3=$(date +%s%3N)
+			#hn="root://data.ci-connect.net"
+			#st3=$(date +%s%3N)
 			#timeout.sh -t $tm xrdcp $xrdargs -f $hn://$sourceFile $baseDir/$localPath 2>&1
-			res=$?
-			dl3=$(date +%s%3N)
-			if [ $res -eq 0 ]; then
+			#res=$?
+			#dl3=$(date +%s%3N)
+			#if [ $res -eq 0 ]; then
 				## pull from trunk succeeded
-				dltm=$((dl3-st3))
-				if [ $2 ]; then
-					updateInfo $st3 $sourceFile $mySz $dltm
-				fi
-				failoverfiles=("${failoverfiles[@]}" $sourceFile)
-				failovertimes=("${failovertimes[@]}" $st2) # time that the failed pull started
+			#	dltm=$((dl3-st3))
+			#	if [ $2 ]; then
+			#		updateInfo $st3 $sourceFile $mySz $dltm
+			#	fi
+			#	failoverfiles=("${failoverfiles[@]}" $sourceFile)
+			#	failovertimes=("${failovertimes[@]}" $st2) # time that the failed pull started
 				## send info out to flume
-				timestamp=$(date +%s)
-				header="[{ \"headers\" : {\"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\" },"
-				body="\"body\" : \"$((st3/1000)),$sourceFile,$mySz,$dltm,$OSG_SITE_NAME,$hn\"}]"
-				echo $header$body > data.json
-				timeout.sh -t 10 curl -X POST -H 'Content-Type: application/json; charset=UTF-8' http://hadoop-dev.mwt2.org:80/ -d @data.json > /dev/null 2>&1
-				rm data.json 2>&1
-			else
-				failfiles=("${failfiles[@]}" $sourceFile)
-				failtimes=("${failtimes[@]}" $st2)	## this is the last time something failed
-				failcodes=("${failcodes[@]}" $res)
-				echo "Stashcp of $sourceFile failed."
-				echo "Command: xrdcp $xrdargs -f root://data.ci-connect.net://$sourceFile $baseDir/$localPath 2>&1"
-				failed=$((failed+1))
-			fi
+			#	timestamp=$(date +%s)
+			#	header="[{ \"headers\" : {\"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\" },"
+			#	body="\"body\" : \"$((st3/1000)),$sourceFile,$mySz,$dltm,$OSG_SITE_NAME,$hn\"}]"
+			#	echo $header$body > data.json
+			#	timeout.sh -t 10 curl -X POST -H 'Content-Type: application/json; charset=UTF-8' http://hadoop-dev.mwt2.org:80/ -d @data.json > /dev/null 2>&1
+			#	rm data.json 2>&1
+			#else
+			#	failfiles=("${failfiles[@]}" $sourceFile)
+			#	failtimes=("${failtimes[@]}" $st2)	## this is the last time something failed
+			#	failcodes=("${failcodes[@]}" $res)
+			#	echo "Stashcp of $sourceFile failed."
+			#	echo "Command: xrdcp $xrdargs -f root://data.ci-connect.net://$sourceFile $baseDir/$localPath 2>&1"
+			#	failed=$((failed+1))
+			#fi
 		fi
 	fi
 }
