update ES index curls and space check
added a check to make sure there is enough space in the destination directory
added destination directory available space and xrdcp version variables to the ES index
stashcp jobs need to be pointed to this new address, which are handled by a collector and then directed to the usual ES host

diff --git a/bin/stashcp b/bin/stashcp
--- a/bin/stashcp
+++ b/bin/stashcp
@@ -88,6 +88,14 @@ function doStashCpSingle {
 	month=$(date +%m)
 
 	## First attempt
+	## Check destination directory for space
+	dirSpace=$(df -k $baseDir | tail -1 | awk '{print $3}')
+	if [ $dirSpace -lt $mySz ]; then
+		noSpace=true
+		echo "Stashcp of $downloadFile failed - not enough space in $baseDir. $dirSpace bytes available, file is $mySz bytes."
+		exit 1
+	fi
+	
 	st1=$(date +%s%3N)
 	downloading_timeout.sh -t $seconds -d $diff -f $baseDir/$localPath -s $mySz xrdcp $xrdargs -f $sourcePrefix://$downloadFile $baseDir/$localPath 
 	res=$?
@@ -101,9 +109,10 @@ function doStashCpSingle {
 		## send info out to flume
 		hn=$sourcePrefix
 		timestamp=$(date +%s)
-		payload="{ \"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\",\"filename\" : \"${downloadFile}\", \"filesize\" : \"${mySz}\", \"download_time\" : \"${dltm}\", \"sitename\" : \"${OSG_SITE_NAME}\"}"
+		xrdcpVersion="$(xrdcp -V 2>&1)"
+		payload="{ \"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\",\"filename\" : \"${downloadFile}\", \"filesize\" : \"${mySz}\", \"download_time\" : \"${dltm}\", \"sitename\" : \"${OSG_SITE_NAME}\", \"destination_space\" : \"${dirSpace}\", \"no_space\" : \"${noSpace}\", \"xrdcp_version\" : \"${xrdcpVersion}\"}"
 		echo $payload > data.json
-		timeout 10 curl -XPOST http://uct2-es-door.mwt2.org:9200/stashcp-$month/rec/ -d @data.json > /dev/null 2>&1 
+		timeout 10 curl -XPOST uct2-int.mwt2.org:9951 -d @data.json > /dev/null 2>&1 
 		rm data.json 2>&1
 	else
 		## pull from local cache failed; try again
@@ -121,9 +130,9 @@ function doStashCpSingle {
 			## send info out to flume
 			hn=$sourcePrefix
 			timestamp=$(date +%s)
-			payload="{ \"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\",\"filename\" : \"${downloadFile}\", \"filesize\" : \"${mySz}\", \"download_time\" : \"${dltm}\", \"sitename\" : \"${OSG_SITE_NAME}\"}"
+			payload="{ \"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\",\"filename\" : \"${downloadFile}\", \"filesize\" : \"${mySz}\", \"download_time\" : \"${dltm}\", \"sitename\" : \"${OSG_SITE_NAME}\", \"destination_space\" : \"${dirSpace}\", \"no_space\" : \"${noSpace}\", \"xrdcp_version\" : \"${xrdcpVersion}\"}"
 			echo $payload > data.json
-			timeout 10 curl -XPOST http://uct2-es-door.mwt2.org:9200/stashcp-$month/rec/ -d @data.json > /dev/null 2>&1
+			timeout 10 curl -XPOST uct2-int.mwt2.org:9951 -d @data.json > /dev/null 2>&1
 			rm data.json 2>&1
 		else 	
 			## second attempt to pull from local cache failed, pulling from trunk
@@ -150,9 +159,9 @@ function doStashCpSingle {
 				failovertimes=("${failovertimes[@]}" $st2) # time that the failed pull started
 				## send info out to flume
 				timestamp=$(date +%s)
-				payload="{ \"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\",\"filename\" : \"${downloadFile}\", \"filesize\" : \"${mySz}\", \"download_time\" : \"${dltm}\", \"sitename\" : \"${OSG_SITE_NAME}\"}"
+				payload="{ \"timestamp\" : \"${timestamp}\", \"host\" : \"${hn}\",\"filename\" : \"${downloadFile}\", \"filesize\" : \"${mySz}\", \"download_time\" : \"${dltm}\", \"sitename\" : \"${OSG_SITE_NAME}\", \"destination_space\" : \"${dirSpace}\", \"no_space\" : \"${noSpace}\", \"xrdcp_version\" : \"${xrdcpVersion}\"}"
 				echo $payload > data.json
-				timeout 10 curl -XPOST http://uct2-es-door.mwt2.org:9200/stashcp-$month/rec/ -d @data.json > /dev/null 2>&1
+				timeout 10 curl -XPOST uct2-int.mwt2.org:9951 -d @data.json > /dev/null 2>&1
 				rm data.json 2>&1
 			else
 				failfiles=("${failfiles[@]}" $downloadFile)
