includes -d flag

diff --git a/stashcp b/stashcp
--- a/stashcp
+++ b/stashcp
@@ -2,7 +2,18 @@
 
 #Usage: stashcp <wanted file> <location to be copied to>
 
-echo "I think my STASHPREFIX is $STASHPREFIX"
+doflag=0
+
+while getopts ":d" opt; do
+    case $opt in 
+	d)
+	    doflag=1
+	    ;;
+	\?)
+	    echo "Invalid option: -$OPTARG" >&2
+	    ;;
+    esac
+done
 
 #set prefix to proper format
 myprefix=$(echo $STASHPREFIX | rev | cut -c 2- | rev)
@@ -11,8 +22,11 @@ if [ ${#myprefix} -lt 6 ]
 then
     myprefix="root://data.ci-connect.net/"
 fi
-
-echo "I think my prefix is $myprefix"
+if [ doflag -eq1 ]
+then
+    echo "I think my STASHPREFIX is $STASHPREFIX"
+    echo "I think my prefix is $myprefix"
+fi
 
 #try pulling from closest cache
 #if xrdcp doesn't finish in 30 minutes, stop
