updating usage info

diff --git a/stashcp b/stashcp
--- a/stashcp
+++ b/stashcp
@@ -28,6 +28,10 @@ while getopts ":drs:l:" opt; do
 	l)
 	    loc=$OPTARG
 	    ;;
+	:) 
+		printf "Missing arguments" >&2
+		echo "$usage" >&2
+		;;
 	\?)
 	    echo "Invalid option: -$OPTARG" >&2
 		echo "$usage" >&2
